name: Deploy microservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker Image
        run: ./scripts/build-image.sh

      # Publish Docker image to container registry
      - name: Publish Docker Image
        run: ./scripts/push-image.sh

      # Recombine and decode kubeconfig file
      - name: Recombine and Decode Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_PART1 }}" > ~/.kube/config
          echo "${{ secrets.KUBE_CONFIG_PART2 }}" >> ~/.kube/config
          echo "${{ secrets.KUBE_CONFIG_PART3 }}" >> ~/.kube/config
          echo "${{ secrets.KUBE_CONFIG_PART4 }}" >> ~/.kube/config
          echo "${{ secrets.KUBE_CONFIG_PART5 }}" >> ~/.kube/config
          chmod 600 ~/.kube/config

      # Install and setup kubectl
      - name: Set Up kubectl
        uses: azure/setup-kubectl@v2
        with:
          version: '1.29.7'

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: ./scripts/deploy.sh
        env:
          KUBECONFIG: ~/.kube/config
