name: Deploy microservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
    
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # Builds the Docker image.
      - name: Build
        run: ./scripts/build-image.sh
      
      # Publishes the Docker image to the container registry.
      - name: Publish
        run: ./scripts/push-image.sh

      # Decode the kubeconfig file and set up kubectl
      - name: Decode kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      # Install and set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v2
        with:
          version: '1.29.7'

      # Deploys the microservice to Kubernetes
      - name: Deploy
        run: ./scripts/deploy.sh
        env:
          KUBECONFIG: ~/.kube/config
